-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYZP6UoRLR3gu7MFI
NQalfl1FxZJCjDXFwb57hBlU7/ugCgYIKoZIzj0DAQehRANCAAQMA6L+VgGyBDB5
JUwR5tPTAMZZprwac2K6tSDLptMcIa4pinU8CuKFfuvyFoFFSnfa6rccZdbeZafL
HYxYA+Gl
-----END PRIVATE KEY-----